### ISSUE TITLE
multiple order confirmation e-mails after installing Zencart plugin into Zencart V1.56c

### ISSUE THREAD

**Issue by amabdelhaliem** [MultiSafepay/Zencart#2] opened 2020-04-14 22:06 UTC
I noticed that orders that were entered after activating a module like "ideal" or "Bancontact" leads to receiving 4 order confirmation e-mails, by both the customer and the admin. Information about this issue is scarce at the moment. I think there might be a compatibility issue with Zencart V1.56c compared to V1.55 for which the MultiSafepay plugin was initially developed. Ideas for how to solve this are very welcome.

**Comment by Jasper-MultiSafepay** [comment] 2020-04-15 09:26
We are unable to reproduce this on 1.56c
Can you make sure the Completed order status is actually set to a valid status?
![image](https://user-images.githubusercontent.com/26003384/79321387-8fabf300-7f0b-11ea-88d5-10a1e3663125.png)

If you are still experiencing multiple order confirmation emails, 
we ask you to send an email with login details to a staging environment to integration@multisafepay.com so we can investigate this further

**Comment by amabdelhaliem** [comment] 2020-04-15 20:45
Dear Jasper,
Thanks a lot! Indeed, changing the "Set Completed Order Status" (in the "MultiSafepay - Connect" module (via "Admin home" then the "Modules" tap then "Payment" then "MultiSafepay - Connect") from "default" to any other value have solved the problem. Now everything is working perfectly except that turning the "Enable payment method icons" to "True" nicely shows the icons of the payment methods but also causes the next steps of the payment procedure to fail and leads to an error page. Switching the icons to "False" restores the procedure!
![MSP icon issue](https://user-images.githubusercontent.com/12950286/79386578-a0d81c80-7f6a-11ea-98c1-a7f8f7a9bbb5.png)

**Comment by Ronald-MultiSafepay** [comment] 2020-04-20 09:14
@amabdelhaliem,
Thank you for reporting this issue.
This issue will be fixed in our next release.
In the meanwhile I will suggest to disable the logo's

**Comment by amabdelhaliem** [comment] 2020-04-20 11:33
Great, thanks Ronald, I'll keep an eye on the next release!

**Comment by Jasper-MultiSafepay** [comment] 2020-07-15 07:52
@amabdelhaliem 
We have released a new version of our plugin (3.1.0)
https://github.com/MultiSafepay/Zencart/releases/tag/3.1.0
This issue should be fixed in this.
We will close this issue but feel free to reopen if this is still happening with this version.

**Closed as completed by Jasper-MultiSafepay** 2020-07-15 07:52 UTC

**Comment by amabdelhaliem** [comment] 2020-07-15 08:43
Dear Jasper,
Thanks a lot for the notification. I will update to the new release a.s.a.p.
Kind regards,
Ahmed

Op wo 15 jul. 2020 om 09:52 schreef Jasper Nadi <notifications@github.com>:
